// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5G0_P_Butrn7F3DDDqtQu7qipvc-HlzU',
    appId: '1:234122021539:web:0b0d35e31d90934dac4d16',
    messagingSenderId: '234122021539',
    projectId: 'canteen-app-dff4a',
    authDomain: 'canteen-app-dff4a.firebaseapp.com',
    storageBucket: 'canteen-app-dff4a.appspot.com',
    measurementId: 'G-YM85JW4N55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJY1HDVvpAHkpsQnqNR4Y-GMvucXlcIM',
    appId: '1:234122021539:android:b91f9303ec821b2cac4d16',
    messagingSenderId: '234122021539',
    projectId: 'canteen-app-dff4a',
    storageBucket: 'canteen-app-dff4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYzksp17u7r46bUmEHkpbDhLCpOkLTy5M',
    appId: '1:234122021539:ios:14d0aeb1df475652ac4d16',
    messagingSenderId: '234122021539',
    projectId: 'canteen-app-dff4a',
    storageBucket: 'canteen-app-dff4a.appspot.com',
    iosClientId: '234122021539-2355vg9uc2octdqd218ij715sibsdr2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYzksp17u7r46bUmEHkpbDhLCpOkLTy5M',
    appId: '1:234122021539:ios:14d0aeb1df475652ac4d16',
    messagingSenderId: '234122021539',
    projectId: 'canteen-app-dff4a',
    storageBucket: 'canteen-app-dff4a.appspot.com',
    iosClientId: '234122021539-2355vg9uc2octdqd218ij715sibsdr2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenApp',
  );
}
